use Ai_Learning_Platform;

-- Display all students.
select * from students;

-- Display only student_name and email from Students table.
select student_name,email from students;

-- Display all courses.
select course_id,course_name from courses; 

-- Display all students from Chennai.
select student_name from students where city="Chennai";

-- Display courses whose fee is greater than ₹7000.
select course_name from courses where fee > 7000;

-- Display instructors having more than 5 years of experience
select instructor_id,instructor_name from instructors where experience_years > 5;

-- Display feedback records with rating 5.
select * from feedback where rating=5;

-- Count total students
select count(*) from students;

-- Count total courses.
select count(*) from courses;

-- Find the maximum course fee.
select max(fee) from courses;

-- Find the minimum course fee.
select min(fee) from courses;

-- Find the average course fee.
select avg(fee) from courses;

-- Display distinct cities from Students table.
select distinct city from students;

-- Display students ordered by name in ascending order
select student_name from students order by student_name;

-- Display courses ordered by fee in descending order
select course_id,course_name,fee from courses order by fee desc;

-- Display top 10 costly courses
select course_id,course_name,fee from courses order by fee desc limit 10;

-- Display students whose name starts with 'A'
select * from students where student_name like "a%";

-- Display students whose email ends with .com.
select * from students where email like "%.com";

-- Display courses whose name contains 'Python'
select * from courses;
select * from courses where course_name like "%python%";

-- Display feedback comments containing the word 'Excellent'.
select comments from feedback where comments like "%Excellent%";

-- Display student names and their enrolled course names.
select s.student_id,s.student_name,c.course_name 
from enrollments as e
join courses as c
on e.course_id=c.course_id
inner join students as s
on s.student_id=e.student_id;

-- Display student names and their assignment marks.
select s.student_name,a.marks_obtained
from students as s
join assignment_Submissions as a
on a.student_id=s.student_id;

-- Display student names and their quiz scores
select s.student_name,q.score
from Quiz_Attempts as q
join students as s
on s.student_id=q.student_id;

-- Display course names and instructor names.
select c.course_name,i.instructor_name
from courses as c
join instructors as i
on i.instructor_id=c.instructor_id; 

-- Display category names and their courses
select course_name,category_name
from courses as c
join categories as cg
on cg.category_id=c.category_id;

-- Count number of students in each city.
select count(student_name) as countstudent,city
from students group by city;

-- Count number of students based on gender
select count(student_name) as gendercount,gender
from students group by gender;

-- Count number of courses in each category
select count(s.course_name) as countcourses,c.category_name
from courses as s
join Categories as c
on c.category_id=s.category_id
group by category_name;

-- Count number of courses handled by each instructor
select count(c.course_name) as coursecount,i.instructor_name
from courses as c
join Instructors as i
on c.instructor_id=i.instructor_id
group by instructor_name;

-- Display total revenue generated by each course.
select sum(p.amount),c.course_name
from courses as c
join Payments as p
on c.course_id=p.course_id
group by c.course_name;

-- Display average quiz score.
select avg(score) as "Average Score" from Quiz_Attempts;

-- Display average assignment marks.
select avg(marks_obtained) as AverageMarks from Assignment_Submissions;

-- Display average rating for each course.
select avg(rating),course_name 
from feedback as b
join courses as c
on c.course_id=b.course_id
group by course_name;

-- Display courses whose fee is between ₹5000 and ₹8000
select  course_name,fee from courses where fee between 5000 and 8000;

-- Display students who have received certificates
select s.student_id,s.student_name,c.certificate_id,c.issue_date
from students as s
join certificates as c
on s.student_id=c.student_id;

-- Display courses that received rating 5.
select c.course_name,f.rating
from courses as c
join feedback as f
on c.course_id=f.course_id
where rating=5;

-- Display total payments received.
select sum(amount) as "Total_Payments" from payments;

-- Display number of feedback entries for each course.
select count(f.feedback_id) as "FeedBack Count",c.course_name 
from courses as c
join feedback as f
on c.course_id=f.course_id
group by course_name;

--  Display courses and their total enrollments
select course_name,count(enrollment_id) as "Total Enrollments"
from courses as c
join enrollments as e
on c.course_id=e.course_id
group by c.course_name;

-- Display students and the payment amount they paid.
select s.student_id,s.student_name,p.amount,c.fee
from students as s
join payments as p
on s.student_id=p.student_id
join courses as c
on c.course_id=p.course_id;

-- Display courses whose fee is greater than the average course fee.
select course_id,course_name from courses where fee > all
(select avg(fee) from courses);

-- Display students who have made payments.
select s.student_id,s.student_name,p.payment_id
from payments as p
join students as s
on s.student_id=p.student_id;

-- Display students who have not made payments.
select s.student_id,s.student_name,p.payment_id
from payments as p
join students as s
on s.student_id=p.student_id
where payment_id is Null;

-- Display the student who scored the highest quiz mark.
select s.student_name,q.score
from students as s
join quiz_attempts as q
on s.student_id=q.student_id
where q.score in 
(select max(score) from quiz_attempts);

-- Display the student who scored the highest assignment mark.
select s.student_name,a.marks_obtained
from students as s
join Assignment_Submissions as a
on s.student_id=a.student_id
where marks_obtained in
(select max(marks_obtained) from Assignment_Submissions);

-- Display the course having the highest fee.
select course_name,fee from courses
where fee=
(select max(fee) from courses);

-- Display instructor names and the average fee of courses handled by them.
select instructor_name,avg(fee)
from instructors as i 
join courses as c
on i.instructor_id=c.instructor_id
group by instructor_name;

-- Display category names and number of courses under each category.
select category_name,count(course_name) as "Course Count"
from categories as c
left join courses as cs
on c.category_id=cs.category_id
group by category_name;

-- Display course names and number of feedbacks received.
select course_name,count(comments)
from courses as c
left join feedback as f
on c.course_id=f.course_id
group by course_name;

-- Display student name, course name, and rating ordered by rating in descending order.
select b.student_name,c.course_name,a.rating from feedback as a 
inner join students as b 
on a.student_id=b.student_id
inner join courses as c
on a.course_id=c.course_id order by a.rating desc;

select*from courses;
select*from students;
select*from categories;
select*from feedback;


















































